language: node_js
node_js:
  - "7"

branches:
  only:
  - master

install:
  - npm install
  - npm run functions

before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli

script:
  - npm run apiKey $FIREBASE_APIKEY
  - npm run build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"

notifications:
  email:
    on_failure: change
    on_success: change
