language: node.js
node_js:
  - "7"

branches:
  only:
  - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

install:
  - npm install
  - npm run functions

script:
  - npm rum apiKey $FIREBASE_APIKEY
  - npm rum build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"

notifications:
  email:
    on_failure: change
    on_success: change
