language: node.js
node_js:
  - "7"

branches:
  only:
  - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm rum apiKey $FIREBASE_APIKEY
  - npm rum build

notifications:
  email:
    on_failure: change
    on_success: change
